services:
# Servicio de base de datos MySQL
  mysql_db:
    image: mysql:8.0
    container_name: pfg_mysql_db
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    # Añadimos un healthcheck para asegurarnos de que la base de datos está lista antes de que la aplicación intente conectarse
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
    # Mapea el puerto del host al puerto del contenedor 
      - "3306:3306"
    volumes:
      # Persistencia de datos (Usa el volumen 'db_data')
      - db_data:/var/lib/mysql
      # Inicialización de la BD (Mapea la carpeta local a la ruta de scripts de MySQL)
      - ./db_init:/docker-entrypoint-initdb.d
      # Configuración de MySQL
      - ./db_init/mysql.cnf:/etc/mysql/conf.d/mysql.cnf

  # ---------------------------------------------------------------------------------------- 
  # API de Dominios Permitidos (Frontend/API)
  allowed_domains_api:
    container_name: pfg_allowed_domains_api
    build:
      context: ./allowed-domains-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      mysql_db:
        condition: service_healthy
    restart: on-failure
    env_file:
      - ./allowed-domains-api/.env
# ----------------------------------------------------------------------------------------
  # Servicio de la aplicación principal Java con Spring Boot
  app:
    build:
      context: ./gest-eventos-app
      dockerfile: Dockerfile
    container_name: pfg_app
    restart: on-failure
    ports:
      - "8081:${SV_PORT}" #Mapea el puerto del host al puerto del contenedor
    depends_on:
      allowed_domains_api:
        condition: service_started # Espera a que el contenedor de dominios inicie
      mysql_db:
        condition: service_healthy # Espera a la DB
    env_file:
      - ./.env
    environment:
        - SPRING_DATASOURCE_URL=${DB_URL}
        - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
        - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
        - SV_PORT=${SV_PORT}
        - MAIL_USERNAME=${MAIL_USERNAME}
        - MAIL_PASSWORD=${MAIL_PASSWORD}
        - API_DOMAIN_URL=${API_DOMAIN_URL}
        - API_SECRET=${API_SECRET}
        - API_DEFAULT_DOMAINS="http://localhost:8000/api http://localhost:8080"

volumes:
  db_data: # Solo se nombra el volumen que necesita ser persistente